name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 0 * * *
jobs:
  build-v8-v11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 8,11 ]
        os: [ bullseye-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "version=$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3"."$4}')" >> $GITHUB_OUTPUT
          echo "minor_version=$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3}')" >> $GITHUB_OUTPUT
          echo "major_version=$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2}')" >> $GITHUB_OUTPUT
          echo "workdir=${{ matrix.major }}/${{ matrix.os }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Copy files
        run: |
          cp files/*.sh ${{ steps.vars.outputs.workdir }}/
          cp files/*.xml ${{ steps.vars.outputs.workdir }}/
          tree .
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.major_version }}-jdk-${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.minor_version }}-jdk-${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-jdk-${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.major_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.minor_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
  build-v18:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 18 ]
        os: [ bullseye-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "version=$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3"."$4}')" >> $GITHUB_OUTPUT
          echo "minor_version=$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3}')" >> $GITHUB_OUTPUT
          echo "major_version=$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2}')" >> $GITHUB_OUTPUT
          echo "workdir=${{ matrix.major }}/${{ matrix.os }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Copy files
        run: |
          cp files/*.sh ${{ steps.vars.outputs.workdir }}/
          cp files/*.xml ${{ steps.vars.outputs.workdir }}/
          tree .
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.major_version }}-jdk-${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.minor_version }}-jdk-${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-jdk-${{ matrix.major }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.major_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.minor_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
