name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 0 * * *
jobs:
  build-v8-v11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 8,11 ]
        os: [ bullseye-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3"."$4}')
          echo ::set-output name=minor_version::$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3}')
          echo ::set-output name=major_version::$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2}')
          echo ::set-output name=workdir::${{ matrix.major }}/${{ matrix.os }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Copy files
        run: |
          cp files/*.sh ${{ steps.vars.outputs.workdir }}/
          cp files/*.xml ${{ steps.vars.outputs.workdir }}/
          tree .
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.major_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.minor_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
  build-v17:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 17 ]
        os: [ bullseye-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})
          echo ::set-output name=version::$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3"."$4}')
          echo ::set-output name=minor_version::$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3}')
          echo ::set-output name=major_version::$(grep 'MAVEN_VERSION=' Dockerfile | awk -F '[=.]' '{print $2}')
          echo ::set-output name=workdir::${{ matrix.major }}/${{ matrix.os }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Copy files
        run: |
          cp files/*.sh ${{ steps.vars.outputs.workdir }}/
          cp files/*.xml ${{ steps.vars.outputs.workdir }}/
          tree .
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.major_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.minor_version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-jdk-${{ matrix.major }}-${{ matrix.os }}
